GET http://localhost:3000/players/

###
GET http://localhost:3000/players/1/

###
get http://localhost:3000/matches/1


###
get http://localhost:3000/players/1/matches/

###
get http://localhost:3000/matches/3/players
###
get http://localhost:3000/players/1/playerScores


###
put http://localhost:3000/players/1/

Content-Type: application/json

{
  "playerName": "Raju"
}
